// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHXNm9YavQudgQqkHyX_hvzfW1eXit-us',
    appId: '1:922496113635:web:1b646223e881000657ded6',
    messagingSenderId: '922496113635',
    projectId: 'mapz-58654',
    authDomain: 'mapz-58654.firebaseapp.com',
    storageBucket: 'mapz-58654.appspot.com',
    measurementId: 'G-WMDTQ4PKD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iqGSv9awgsDsp1Kk7_1zQXDEyGM7K6w',
    appId: '1:922496113635:android:f5cf59c28394552a57ded6',
    messagingSenderId: '922496113635',
    projectId: 'mapz-58654',
    storageBucket: 'mapz-58654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-PJvWX1L_IOACc8XceppMtKmjhCEyEMY',
    appId: '1:922496113635:ios:84356911c480e87e57ded6',
    messagingSenderId: '922496113635',
    projectId: 'mapz-58654',
    storageBucket: 'mapz-58654.appspot.com',
    iosBundleId: 'com.example.batch2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-PJvWX1L_IOACc8XceppMtKmjhCEyEMY',
    appId: '1:922496113635:ios:67064df115e3a29f57ded6',
    messagingSenderId: '922496113635',
    projectId: 'mapz-58654',
    storageBucket: 'mapz-58654.appspot.com',
    iosBundleId: 'com.example.batch2App.RunnerTests',
  );
}
